# Generated by Django 3.2.6 on 2024-12-19 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('starting_date', models.DateField(default=datetime.datetime.now)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('status', models.CharField(choices=[('WRITING', 'Writing'), ('EDITING', 'Editing'), ('MIXING', 'Mixing'), ('MASTERING', 'Mastering'), ('FINISHED', 'Finished')], default='WRITING', max_length=10)),
                ('notes', models.TextField()),
            ],
        ),
    ]
